### PR TITLE
upgrade go version 

### PR DESCRIPTION
**Pull request by nar10z**
go 1.19
rethinkdb 2.4.2 support

### CODE REVIEW

**Comment by nar10z** [comment]
@oliver006 Hello! Please check. 
exporter don't work with last rethinkdb version, i fixed it

**Comment by oliver006** [comment]
Thanks for the PR!
What exactly was the issue and what fixed it?

**Comment by nar10z** [comment]
strange...
I went to run the code in which there was a problem, but this time everything worked stably.

The error was (as it seemed to me) in the parsing of the rethinkdb version, in the package gopkg.in/rethinkdb/rethinkdb-go.v6

**Comment by nar10z** [comment]
ok, maybe it's my local problem
i'm close PM

**Pull request closed without merging**
